"""Generate a less spoiler-prone blind-play copy of hotel_game.py."""

from __future__ import annotations

import ast
import base64
import io
import os
import sys
import tokenize
from tokenize import TokenInfo


HEADER = '''# Generated by make_blind.py. Do not edit by hand.
# Strings are encoded to reduce accidental spoilers during blind play.
import base64 as _blind_b64


def _S(value):
    return _blind_b64.b64decode(value.encode("ascii")).decode("utf-8")

'''


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    root = os.path.dirname(os.path.abspath(__file__))
    source = args[0] if args else os.path.join(root, "hotel_game.py")
    target = args[1] if len(args) > 1 else os.path.join(root, "hotel_game_blind.py")
    with open(source, "rb") as handle:
        raw = handle.read()
    transformed = blind_source(raw)
    with open(target, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(transformed)
    print("wrote {}".format(target))
    return 0


def blind_source(raw: bytes) -> str:
    output = []
    stream = io.BytesIO(raw).readline
    for token in tokenize.tokenize(stream):
        if token.type in (tokenize.ENCODING, tokenize.COMMENT):
            continue
        if token.type == tokenize.STRING:
            replacement = encode_string_token(token)
            if replacement is not None:
                token = TokenInfo(token.type, replacement, token.start, token.end, token.line)
        output.append(token)
    body = tokenize.untokenize(output)
    if isinstance(body, bytes):
        body = body.decode("utf-8")
    return HEADER + body


def encode_string_token(token: TokenInfo) -> str | None:
    try:
        value = ast.literal_eval(token.string)
    except (SyntaxError, ValueError):
        return None
    if not isinstance(value, str):
        return None
    encoded = base64.b64encode(value.encode("utf-8")).decode("ascii")
    return '_S("{}")'.format(encoded)


if __name__ == "__main__":
    raise SystemExit(main())

